replicaCount: 1

image:
  repository: ghcr.io/pozitp/web-lab2
  tag: d99d898ede9ae17d90cc5c470b548775a3d8362f
  pullPolicy: IfNotPresent
  pullSecrets: [ ]

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  host: web-lab2.local
  path: /
  tls:
    enabled: false
    secretName: ""

resources: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }
