replicaCount: 1

image:
  repository: ghcr.io/pozitp/web-lab2
  tag: 00a835953b4ae51c56ee81ca18ee2bf79f9d86f2
  pullPolicy: IfNotPresent
  pullSecrets: [ ]

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  host: web-lab2.local
  path: /
  tls:
    enabled: false
    secretName: ""

resources: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }
