replicaCount: 1

image:
  repository: ghcr.io/pozitp/web-lab2
  tag: 7f1c4aaeb1bac9e55b9a6336ee9636e08ce14b6d
  pullPolicy: IfNotPresent
  pullSecrets: [ ]

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  host: web-lab2.local
  path: /
  tls:
    enabled: false
    secretName: ""

resources: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }
